name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: astra-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libfuse-dev pkg-config gostsum gnupg libgost-dev libgpgme11 libgpgme11-dev check
    - name: Build tests
      run: gcc -Wall test_fusexmp.c -o test_fusexmp -lcheck -lgpgme -lgpg-error -lgost
    - name: Run tests
      run: ./test_fusexmp
